Update sync_and_linux_build.yml

diff --git a/.github/workflows/sync_and_linux_build.yml b/.github/workflows/sync_and_linux_build.yml
--- a/.github/workflows/sync_and_linux_build.yml
+++ b/.github/workflows/sync_and_linux_build.yml
@@ -40,8 +40,8 @@ jobs:
       - name: Create markdown file
         run: |
           cd libs
-          echo "| module | compiler | old version | new version | cmake result | build.log |" > result.md
-          echo "| :------: | :------: | :------: | :------: | :------: | :------: |" >> result.md
+          echo "| module | compiler | available version | cmake result | build.log |" > result.md
+          echo "| :------: | :------: | :------: | :------: | :------: |" >> result.md
       - name: Archive libs
         uses: actions/upload-artifact@v2
         with:
@@ -85,14 +85,13 @@ jobs:
         run: |
           cd module/${{ matrix.module }}
           cmake ${{matrix.config.command}} "${{matrix.config.compiler}}" -S . -B ./build 2>&1 | tee ../../libs/dll/${{matrix.config.path}}/${{ matrix.module }}/build.log && cmake --build ./build --target install 2>&1 | tee -a ../../libs/dll/${{matrix.config.path}}/${{ matrix.module }}/build.log
-          new_version=$(grep "VERSION" version.txt | cut -d' ' -f2 | tr '\n' '.' | sed 's/\.$//')
-          old_version=$(grep "VERSION" ../../libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/version.txt | cut -d' ' -f2 | tr '\n' '.' | sed 's/\.$//')
+          available_version=$(grep "VERSION" ../../libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/version.txt | cut -d' ' -f2 | tr '\n' '.' | sed 's/\.$//')
           cd ../../libs
-          if [ $? -ne 0 ] || [ "$(echo -e "$old_version\n$new_version" | sort -V | tail -n1)" = "$old_version" ]
+          if [ $? -ne 0 ]
           then
-            echo "| ${{ matrix.module }} | ${{ matrix.config.path}} | $old_version | $new_version | <span style="color:red">&#x274C; failed</span> | [build_information](./libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/build.log) |" >> result.md
+            echo "| ${{ matrix.module }} | ${{ matrix.config.path}} | $available_version | <span style=\"color:red\">failed</span> | [build information](/libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/build.log "build.log") |" >> result.md
           else
-            echo "| ${{ matrix.module }} | ${{ matrix.config.path}} | $old_version | $new_version | <span style="color:green">&#x2705; succeeded</span> | [build_information](./libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/build.log) |" >> result.md
+            echo "| ${{ matrix.module }} | ${{ matrix.config.path}} | $available_version | <span style=\"color:green\">succeeded</span> | [build information](/libs/dll/${{ matrix.config.path }}/${{ matrix.module }}/build.log "build.log") |" >> result.md
           fi
       - name: Archive libs
         uses: actions/upload-artifact@v2
@@ -102,6 +101,7 @@ jobs:
   push_repository:
     needs: process_repository
     runs-on: ubuntu-latest
+    if: always()
     steps:
     - name: Download cloned_libs
       uses: actions/download-artifact@v2
